#!/usr/bin/env bash
# Generates this deployment's own secrets and writes docker/.env. Safe to re-run: it never
# overwrites anything that already exists, because rotating the JWT key invalidates live sessions
# and rotating the crypto key makes every stored secret-field value unreadable.
set -euo pipefail

cd "$(dirname "$0")"
mkdir -p data/keys data/mysql

if [ ! -f data/keys/privateKey.pem ]; then
  echo "generating a JWT keypair for this deployment"
  openssl genrsa -out data/keys/privateKey.pem 2048 2>/dev/null
  openssl rsa -in data/keys/privateKey.pem -pubout -out data/keys/publicKey.pem 2>/dev/null
  # Read by the API's non-root user.
  chmod 644 data/keys/privateKey.pem data/keys/publicKey.pem
else
  echo "keeping the existing JWT keypair (rotating it would sign every live session out)"
fi

if [ ! -f .env ]; then
  echo "writing .env"
  {
    echo "# Generated by bootstrap.sh. These are THIS deployment's secrets — do not commit them."
    echo "MYSQL_ROOT_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)"
    echo "MYSQL_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)"
    # AES-256 for secret-field values (C-12). Losing this makes stored secrets unreadable.
    echo "NOTEBOX_CRYPTO_KEY_1=$(openssl rand -base64 32)"
    echo "NEXT_PUBLIC_API_BASE_URL=http://localhost:8080/api"
    echo "NOTEBOX_CORS_ORIGINS=http://localhost:3000"
    echo "NOTEBOX_SIGNUP_ENABLED=true"
  } > .env
  chmod 600 .env
else
  echo "keeping the existing .env (it holds the key your stored secrets were encrypted with)"
fi

echo
echo "ready — now run:  docker compose up -d --build"
